foodwebsite/food/urls.py
from django.urls import path
from . import views
# import path urls - zaimportowanie urls
# . import views - ze wszystkich widokow

app_name = 'food'

urlpatterns = [
     # /food stworzenie strony homepage, '' - zostawiamy puste, szukamy funkcji index w views
    path('', views.index, name='index'),

    # /food/1  /food/<restaurant_id>stworzenie podstrony
    path('<int:restaurant_id>/', views.detail, name='detail'),

    path('add/restaurant/', views.add_restaurant, name='add-restaurant'),

    path('add/food/', views.add_food, name='add-food'),

    path('add/report/', views.get_report, name='add-report'),

    path('article/', views.article, name='article'),
    
    path('add/article/', views.add_article, name='add-article')

]

foodwebsite/foodwebsite/urls.py
from django.contrib import admin
from django.urls import include, path
# import include - dodac inne pliki

urlpatterns = [
    # admin url
    path('admin/', admin.site.urls),
    # dodac food url 
    path('food/', include('food.urls')), 
]

foodwebsite/food/models.py
from django.db import models

# Create your models here.

# pokazuje zmianie, terminal: python manage.py makemigrations food
# konwertuje do tabeli sql
# dodaje wszystkie zmiany , terminal: python manage.py migrate

class Restaurant(models.Model):
     name = models.CharField(max_length=250)
     restaurant_type = models.CharField(max_length=150)
     city = models.CharField(max_length=250)
     restaurant_logo = models.CharField(max_length=1000)

     def __str__(self):
          return "{}".format(self.name)

     class Meta:
        verbose_name = "Restauracja"
        verbose_name_plural = "Restauracje"

class Food(models.Model):
     #klucz obcy do restaurant
     restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
     food_name = models.CharField(max_length=250)
     food_type = models.CharField(max_length=150)
     food_price = models.IntegerField(default=1)

     def __str__(self):
          return "{}".format(self.food_name)

     class Meta:
        verbose_name = "Potrawa"
        verbose_name_plural = "Potrawy" 

class Deliver(models.Model):
     restaurants = models.ManyToManyField(Restaurant)
     name = models.CharField(max_length=250)
     city = models.CharField(max_length=250)
     index_id = models.CharField(max_length=250, blank=False)

     def __str__(self):
          return "{}".format(self.name)

class Article(models.Model):
     title = models.CharField(max_length=60)
     content = models.TextField()
     author = models.CharField(max_length=60)

     def __str__(self):
          return "{}".format(self.title)

foodwebsite/food/forms.py
from django import forms
from .models import Restaurant, Food, Article

# Create the form class.
class RestaurantForm(forms.ModelForm):
	class Meta:
		model = Restaurant
		fields = ['name', 'restaurant_type', 'city', 'restaurant_logo']

class FoodForm(forms.ModelForm):
	class Meta:
		model = Food
		fields = ['restaurant', 'food_name', 'food_type', 'food_price']

class ArticleForm(forms.ModelForm):
	class Meta:
		model = Article
		fields = ['title', 'content', 'author']


class ReportForm(forms.ModelForm):
	class Meta:
		model = Food
		fields = ['restaurant']		
	CHOICES = (('yes', 'Yes'),('no', 'No'),)
	order_price = forms.ChoiceField(label='Sort (price)?', choices=CHOICES)
	total_price = forms.ChoiceField(label='Total price', choices=CHOICES)
	avg_price = forms.ChoiceField(label='Average (price)', choices=CHOICES)



		
		

foodwebsite/food/views.py
# importujemy get_object_or_404 do obslugiwania bledow
from django.shortcuts import render, get_object_or_404
# importujemy z modeli Restauracje
from .models import Restaurant, Food, Article
# importujemy formularz
from .forms import RestaurantForm, FoodForm, ArticleForm, ReportForm

from django.http import HttpResponseRedirect
# Importowanie sumy, średniej
from django.db.models import Sum, Avg



# dodanie funkcji z widokiem
def index(request):
     # polaczenie z database i pobranie wszystkich restauracji z bazy danych
     all_restaurants = Restaurant.objects.all()
     content = {'all_restaurants': all_restaurants}
     # zwracamy,  importujemy templete z folderu food i informacje o restauracjach
     return render(request, 'food/index.html', content)

def detail(request, restaurant_id):
     # Jezeli adres jest niepoprawny to wyswietla sie blad
     restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
     return render(request, 'food/detail.html', {'restaurant': restaurant})

def article(request):
     # polaczenie z database i pobranie wszystkich restauracji z bazy danych
     all_articles = Article.objects.all()
     content = {'all_articles': all_articles}
     # zwracamy,  importujemy templete z folderu food i informacje o restauracjach
     return render(request, 'food/article.html', content)



def add_restaurant(request):
    # jeżeli request.POST (przesłano formularz metodą POST) przetwórz formularz
    if request.method == 'POST':
        #przetwórz formularz zgodnie z danymi z POST
        form = RestaurantForm(request.POST)
        # sprawdz validace formularza:
        if form.is_valid():
            #zapisuje obiekt w bazie danych
            form.save()
            # Przekierowanie na strone glowna
            return HttpResponseRedirect('/food/add/restaurant/')

    #jeżeli nie przesłano formularza wyświetl czysty formularz
    else:
        form = RestaurantForm()

    return render(request, 'food/restaurant_form.html', {'form': form})


def add_food(request):
    # jeżeli request.POST (przesłano formularz metodą POST) przetwórz formularz
    if request.method == 'POST':
        #przetwórz formularz zgodnie z danymi z POST
        form = FoodForm(request.POST)
        # sprawdz validace formularza:
        if form.is_valid():
            #zapisuje obiekt w bazie danych
            form.save()
            # Przekierowanie na strone glowna
            return HttpResponseRedirect('/food/add/food/')

    #jeżeli nie przesłano formularza wyświetl czysty formularz
    else:
        form = FoodForm()

    return render(request, 'food/food_form.html', {'form': form})


def add_article(request):
    # jeżeli request.POST (przesłano formularz metodą POST) przetwórz formularz
    if request.method == 'POST':
        #przetwórz formularz zgodnie z danymi z POST
        form = ArticleForm(request.POST)
        # sprawdz validace formularza:
        if form.is_valid():
            #zapisuje obiekt w bazie danych
            form.save()
            # Przekierowanie na strone glowna
            return HttpResponseRedirect('/food/add/article/')

    #jeżeli nie przesłano formularza wyświetl czysty formularz
    else:
        form = ArticleForm()

    return render(request, 'food/food_form.html', {'form': form})





def get_report(request):
    # jeżeli request.POST (przesłano formularz metodą POST) przetwórz formularz
    if request.method == 'POST':
        #przetwórz formularz zgodnie z danymi z POST
        form = ReportForm(request.POST)
        # sprawdz validace formularza:
        if form.is_valid():
            restaurant_id = form.data['restaurant']
            order_price= form.data['order_price']
            total_price = form.data['total_price']
            avg_price = form.data['avg_price']
            option_select = 'yes'
            price_boolean = False
            avg_boolean = False

            # Filtorwanie - znaleznienie restauracji po id
            get_restaurant = Restaurant.objects.filter(id=restaurant_id)
            # Filtorwanie - znaleznienie potraw po id restauracji
            food_list = Food.objects.filter(restaurant = restaurant_id)

            if order_price == option_select:
                food_list = food_list.order_by('food_price')

            if total_price == option_select:
                total_price = food_list.aggregate(Sum('food_price'))
                price_boolean = True

            if avg_price == option_select:
                avg_price= food_list.aggregate(Avg('food_price'))
                avg_boolean = True

            return render(request, 'food/report.html',
            { 
                'restaurants': get_restaurant, 
                'foods': food_list, 
                'total': total_price, 
                'avg_price': avg_price , 
                'price_statement': price_boolean,
                'avg_statement': avg_boolean
            })

    #jeżeli nie przesłano formularza wyświetl czysty formularz
    else:
        form = ReportForm()

    return render(request, 'food/report_form.html', {'form': form})

foodwebsite/food/templates/food/article.html
{% extends 'food/base.html' %}


     {% block content %}

     <main class="main main--article u-bg">

          {% if all_articles %}

               {% for article in all_articles %}
               <article class="article">
                    <div class="row">
                         <div class="article__box">
                              <div class="article__content">
                                   <i class="article__icon fa fa-book" aria-hidden="true"></i>
                                   <h3 class="heading-three">{{article.title}}.</h3>
                                   <p class="article__paragraph">{{article.content}} </p>

                                   <figure class="author">
                                        {% load static %}
                                        <img class="author__img" src="{% static 'food/img/avatar.png' %}" alt="Awatar">
                                        <figcaption class="author__name">By {{article.author}}</figcaption>
                                   </figure>
                              </div>
                              <div class="article__photo-box">
                                   {% load static %}
                                   <img src="{% static 'food/img/city.png' %}" alt="City" class="article__photo">
                              </div>
                         </div>
                    </div>
               </article>
               {% endfor %}
          {% endif %}

          <a href="{% url 'food:add-article' %}" class="navigation__link navigation__link--active navigation__link--add-article">Add Articles</a>
     </main>
     {% endblock %}

foodwebsite/food/templates/food/article_form.html
{% extends 'food/base.html' %}

     {% block content %}

     <div class="main main-form u-bg">
          
          <form action="" method="post" enctype="multipart/form-data" class="form">
               
               <div class="form__box">
                    <h2 class="heading-second">Article</h2>
                    {% csrf_token %}
                    {% include 'food/form-template.html' %}
                    <div class="form__group">
                         <label for="submit" class="form__label">&nbsp;</label>
                         <input class="form__input form__input--submit" type="submit" id="submit" value="Submit!">
                    </div>
               </div>

          </form>
     
     </div>
     {% endblock %}

foodwebsite/food/templates/food/base.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <meta name="author" content="Karol Kozer s14575">
     <link rel="stylesheet" href="https://use.fontawesome.com/2eccaf5f1b.css">
     {% load staticfiles %}
     <link rel="stylesheet" href="{% static 'food/base.css' %}">
     <link rel="stylesheet" href="{% static 'food/home.css' %}">
     <link rel="stylesheet" href="{% static 'food/detail.css' %}">
     <link rel="stylesheet" href="{% static 'food/form.css' %}">
     <link rel="stylesheet" href="{% static 'food/print.css' %}">
     <link rel="stylesheet" href="{% static 'food/article.css' %}"> 
     <title>Easy Order</title>
</head>
<body>

     <nav class="navigation">
          <div class="row">
               <div class="navigation__content">
                    <div class="navigation__logo">
                         <a href="{% url 'food:index' %}" class="navigation__icon-link">
                              <i class="navigation__icon fa fa-taxi" aria-hidden="true"></i>
                         </a>
                    </div>

                    <ul class="navigation__nav">

                         <li class="navigation__item"><a href="{% url 'food:index' %}" class="navigation__link">Home</a></li>

                         <li class="navigation__item"><a href="{% url 'food:add-restaurant' %}" class="navigation__link">Add Restaurant</a></li>

                         <li class="navigation__item"><a href="{% url 'food:add-food' %}" class="navigation__link">Add Food</a></li>

                         <li class="navigation__item"><a href="{% url 'food:add-report' %}" class="navigation__link">Report</a></li>

                         <li class="navigation__item"><a href="{% url 'food:article' %}" class="navigation__link">Articles</a></li>
                    </ul>
               </div>
          </div>
     </nav>

     
     {% block content %}
     {% endblock %}

     <footer class="footer">
          <div class="row">
               <div class="footer__content">
                    <div class="footer__logo">
                         <a href="{% url 'food:index' %}" class="footer__nav-link">
                              <i class="footer__icon fa fa-taxi" aria-hidden="true"></i>
                         </a>
                    </div>
                    <ul class="footer__nav">
                         <li class="footer__item"><a href="{% url 'food:index' %}" class="footer__link">Home</a></li>
                         <li class="footer__item"><a href="{% url 'food:add-restaurant' %}" class="footer__link">Restaurant</a></li>
                         <li class="footer__item"><a href="{% url 'food:add-food' %}" class="footer__link">Food</a></li>
                         <li class="footer__item"><a href="{% url 'food:add-report' %}" class="footer__link">Report</a></li>
                         <li class="footer__item"><a href="{% url 'food:article' %}" class="footer__link">Article</a></li>
                    </ul>
                    <ul class="footer__nav-social">
                         <li class="footer__item"><a href="#" class="footer__link footer__link--social"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                         <li class="footer__item"><a href="#" class="footer__link footer__link--social"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                    </ul>
               </div>

               <p class="footer__info">Copyright © 2017 by Easy Order. All rights reserved.</p>
          </div>
     </footer>
     
</body>
</html>

foodwebsite/food/templates/food/detail.html
{% extends 'food/base.html' %}

     {% block content %}

          <section class="section section__restaurant u-bg">
               <div class="restaurant">
                    <div class="restaurant__logo-box">
                         <img src="{{ restaurant.restaurant_logo }}" alt="Logo" class="restaurant__logo">
                    </div>

                    <div class="restaurant__info">
                         <h3 class="restaurant__name">{{ restaurant.name }}</h3>
                         <h4 class="restaurant__menu">Menu:</h4>
          
                         <ul class="restaurant__list">
                              {% for food in restaurant.food_set.all %}
                                   <li class="restaurant__item">
                                        <span class="restaurant__food"> {{ food.food_name }} </span>
                                        <span class="restaurant__food-price">/ {{ food.food_price }} zł</span>
                                   </li>
                              {% endfor %}
                         </ul>
                    </div> 
               </div>
          </section>

     {% endblock %}

foodwebsite/food/templates/food/food_form.html
{% extends 'food/base.html' %}

     {% block content %}

     <div class="main main-form u-bg">

          <form action="" method="post" enctype="multipart/form-data" class="form">
               
               <div class="form__box">
                    <h2 class="heading-second">Form Food</h2>
                    {% csrf_token %}
                    {% include 'food/form-template.html' %}
                    <div class="form__group">
                         <label for="submit" class="form__label">&nbsp;</label>
                         <input class="form__input form__input--submit" type="submit" id="submit" value="Submit!">
                    </div>
               </div>

          </form>
     
     </div>
     {% endblock %}

foodwebsite/food/templates/food/form-template.html
{% for field in form  %}

     <div class="form__group">
          <span class="error">{{ field.errors }}</span>
          <label for="res" class="form__label">{{ field.label_tag }}</label>
          <div class="form__input">{{ field }}</div>
     </div>
{% endfor %}

foodwebsite/food/templates/food/index.html
{% extends 'food/base.html' %}

     {% block content %}

          <header class="header u-bg">
               <div class="header__text-box">
                    <h1 class="heading-primary">
                         <span class="heading-primary--main">Easy Order</span>
                         <span class="heading-primary--second">Find restaurants that deliver near you</span>
                    </h1>
                    
                    <!-- Sprawdzenie czy sa restauracje -->
                    {% if all_restaurants %}
                    <div class="header__restaurant">
                         {% for restaurant in all_restaurants %}
                              <!-- <a href="{{ restaurant.id }}">{{ restaurant.name }}</a> -->
                              <!-- food/ to jest stale -->
                              <a class="btn btn--white" href="{% url 'food:detail' restaurant.id  %}">{{ restaurant.name }}</a>
                         {% endfor %}
                    </div>
                    {% else %}
                         <p class="text">We do not have any restaurants</p>
                    {% endif %}

               </div>
          </header>

     {% endblock %}

foodwebsite/food/templates/food/report.html
{% extends 'food/base.html' %}

     {% block content %}
     
     <div class="main main-form u-bg">

          <div class="report">
               {% if restaurants %}
                    {% for restaurant in restaurants %}

                    <h2 class="heading-second heading-second--report">Report {{ restaurant.name }}</h2>

                    <table class="report__result">
                         <tbody>
                              <tr>
                                   <th>Dish</th> 
                                   <th>Price</th>
                              </tr>
                              {% for food in foods %}
                              <tr>
                                   <td>{{ food.food_name }}</td> 
                                   <td>{{ food.food_price }} zł</td>
                              </tr>
                              {% endfor %}
                         </tbody>
                    </table>

                    {% endfor %}
               {% endif %}

               {% if price_statement %}
                    <p class="report__total">
                         Total: 
                         <span class="report__total-price">{{ total.food_price__sum }}</span> zł
                    </p>
               {% endif %}

               {% if avg_statement %}
                    <p class="report__total">
                         Average: 
                         <span class="report__total-price">{{ avg_price.food_price__avg }}</span> zł
                    </p>
               {% endif %}
          </div>
     
     </div>
     
     {% endblock %}

foodwebsite/food/templates/food/report_form.html
{% extends 'food/base.html' %}

     {% block content %}
     
     <div class="main main-form u-bg">
               
          <form method="post" class="form">
               
               <div class="form__box">
                    <h2 class="heading-second">Report</h2>
                    {% csrf_token %}
                    {% include 'food/form-template.html' %}
                    <div class="form__group">
                         <label for="submit" class="form__label">&nbsp;</label>
                         <input class="form__input form__input--submit" type="submit" id="submit" value="Submit!">
                    </div>
               </div>

          </form>
     
     </div>
     
     {% endblock %}

foodwebsite/food/templates/food/restaurant_form.html
{% extends 'food/base.html' %}

     {% block content %}

     <div class="main main-form u-bg">

          <form action="" method="post" enctype="multipart/form-data" class="form">
               
               <div class="form__box">
                    <h2 class="heading-second">Form Restaurant</h2>
                    {% csrf_token %}
                    {% include 'food/form-template.html' %}
                    <div class="form__group">
                         <label for="submit" class="form__label">&nbsp;</label>
                         <input class="form__input form__input--submit" type="submit" id="submit" value="Submit!">
                    </div>
               </div>

          </form>
     
     </div>
     {% endblock %}